# Generated by Django 5.1.1 on 2024-12-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=15)),
                ('score1', models.IntegerField()),
                ('player2', models.CharField(max_length=15)),
                ('score2', models.IntegerField()),
                ('dateTime', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
    ]
