version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgre
      POSTGRES_USER: frgojard
      POSTGRES_PASSWORD: passdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data: